[tool.poetry]
name = "project"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
atoti = "*"
# Pylint currently crashes on pandas 1.1.5.
# See https://github.com/PyCQA/pylint/issues/3836
pandas = "1.1.4"
python = "^3.7.4"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
pytest = "*"
pylint = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pylint."messages control"]
ignore = [".venv"]
disable = [
  # Broken, see https://github.com/PyCQA/pylint/issues/3507
  "isinstance-second-argument-not-valid-type",
  # Do not force docstrings
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
]
good-names = ["at", "h", "l", "m"]
