name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test
    env:
      ATOTI_HIDE_EULA_MESSAGE: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Set up Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --no-modify-path
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: poetry run black --check project/ tests/
      - run: poetry run isort --check project/ tests/
      - run: poetry run pylint project/ tests/
      - run: poetry run pytest
